export const benchmark = {
  sourceLabel: "Benchmark interno atual do repositório",
  generatedAt: "2026-04-09T19:43:38.976573+00:00",
  score: 88.94,
  timelineConsistencyScore: 90.91,
  casesEvaluated: 11,
  metrics: [
    { label: "Evidência ancorada", value: 91.67 },
    { label: "Confiabilidade", value: 98.16 },
    { label: "Utilidade jurídica", value: 81.82 },
  ],
  note:
    "Métricas exibidas como benchmark interno atual do checkout local. Quando usadas em contexto público, devem permanecer rotuladas como benchmark interno ou demo data.",
};

export const currentUser = {
  name: "Marina Teles",
  role: "Líder médico-jurídica",
  workspace: "Atlas Perícias",
  plan: "Pro",
  initials: "MT",
};

export const quickActions = [
  { label: "Novo caso", icon: "plus" },
  { label: "Importar documentos", icon: "upload" },
  { label: "Abrir fila de revisão", icon: "review" },
];

export const cases = [
  {
    id: "afastamento-lima",
    title: "Afastamento ocupacional | Ana Lima",
    subtitle: "Nexo temporal entre atestados, receita e perícia",
    client: "Ana Clara Lima",
    type: "Afastamento e atestado",
    status: "Em revisão",
    statusTone: "warning",
    documentsCount: 12,
    recentActivity: "Atualizado há 18 min",
    readiness: 82,
    confidence: 91,
    timelineConsistency: 96,
    pendingReview: 3,
    regressions: 0,
    artwork: "ember",
    coverLabel: "Afastamento",
    updatedAt: "2026-04-10",
    moments: ["document_date segura", "afastamento observado", "receita correlata"],
    categories: ["continue", "review", "high-confidence"],
    summary:
      "Caso com afastamento observado e conjunto documental convergente. A revisão humana está concentrada em conflito de CID secundário e granularidade do período afastado.",
    stats: [
      { label: "Prontidão jurídica", value: "82/100" },
      { label: "Timeline consistente", value: "96/100" },
      { label: "Pendências", value: "3" },
    ],
    documents: [
      {
        id: "doc-atestado-ana",
        title: "Atestado médico inicial",
        type: "Atestado médico",
        pages: 2,
        fingerprint: "sha256: 2df9...48b2",
        custodyState: "Preservado com hash local",
        processingStatus: "Layer5 derivado gerado",
        origin: "digital_nativo",
        issuedAt: "2026-03-02",
        warnings: [],
        ocrMode: "native_text",
        canonicalSignals: [
          { field: "document_date", value: "2026-03-02", state: "observed" },
          { field: "patient", value: "ANA CLARA LIMA", state: "observed" },
          { field: "provider", value: "DRA. RENATA SOUZA", state: "observed" },
          { field: "cids", value: "M54.5", state: "observed" },
        ],
        pagesData: [
          {
            number: 1,
            title: "Página 1",
            snippet:
              "Atesto para os devidos fins que Ana Clara Lima necessita de afastamento laboral por 10 dias, a partir de 02/03/2026.",
            evidenceBox: "bbox [112, 244, 822, 332]",
          },
          {
            number: 2,
            title: "Página 2",
            snippet:
              "CID M54.5. Reavaliação em 12/03/2026. CRM 557812.",
            evidenceBox: "bbox [108, 156, 792, 224]",
          },
        ],
        relatedEvents: ["ev-afastamento-observado", "ev-emissao-atestado"],
      },
      {
        id: "doc-receita-ana",
        title: "Receituário complementar",
        type: "Receituário",
        pages: 1,
        fingerprint: "sha256: c91e...2250",
        custodyState: "Preservado com hash local",
        processingStatus: "Layer4 normalizado",
        origin: "digital_nativo",
        issuedAt: "2026-03-03",
        warnings: [
          "Documento classificado corretamente como receituário; não há promoção indevida para atestado.",
        ],
        ocrMode: "native_text",
        canonicalSignals: [
          { field: "document_type", value: "receituario", state: "observed" },
          { field: "patient", value: "ANA CLARA LIMA", state: "observed" },
          { field: "medication", value: "Ciclobenzaprina 5mg", state: "observed" },
        ],
        pagesData: [
          {
            number: 1,
            title: "Página única",
            snippet: "Receito Ciclobenzaprina 5mg por 7 dias. Retorno se persistir lombalgia.",
            evidenceBox: "bbox [126, 280, 810, 364]",
          },
        ],
        relatedEvents: ["ev-prescricao-analgesica"],
      },
    ],
    events: [
      {
        id: "ev-emissao-atestado",
        date: "2026-03-02",
        type: "document_issue_date",
        title: "Emissão do atestado inicial",
        description: "Data documental observada no atestado com página, snippet e bbox exatos.",
        state: "observed",
        confidence: 0.98,
        provenanceStatus: "anchored",
        reviewState: "confirmed",
        evidenceRef: "Atestado médico inicial · pág. 1",
      },
      {
        id: "ev-afastamento-observado",
        date: "2026-03-02",
        type: "afastamento_medico",
        title: "Afastamento laboral de 10 dias",
        description: "Evento observado com período explícito no texto documental.",
        state: "observed",
        confidence: 0.95,
        provenanceStatus: "anchored",
        reviewState: "confirmed",
        evidenceRef: "Atestado médico inicial · pág. 1",
      },
      {
        id: "ev-prescricao-analgesica",
        date: "2026-03-03",
        type: "prescricao",
        title: "Prescrição analgésica complementar",
        description: "Receituário associado ao mesmo episódio clínico.",
        state: "observed",
        confidence: 0.9,
        provenanceStatus: "anchored",
        reviewState: "confirmed",
        evidenceRef: "Receituário complementar · pág. 1",
      },
    ],
    reviewItems: [
      {
        id: "rv-afastamento-fim",
        field: "estimated_leave_end",
        value: "2026-03-12",
        reason: "Derivado do período de 10 dias; manter claramente rotulado como estimado.",
        state: "needs_review",
        provenanceStatus: "estimated",
      },
      {
        id: "rv-cid-secundario",
        field: "cid_secondary",
        value: "M62.8",
        reason: "CID secundário aparece apenas em anotação lateral com OCR parcial.",
        state: "needs_review",
        provenanceStatus: "inferred",
      },
    ],
  },
  {
    id: "parecer-moura",
    title: "Parecer CID | Bruno Moura",
    subtitle: "Linha do tempo robusta com parecer, laudo e protocolo",
    client: "Bruno César Moura",
    type: "Parecer médico-jurídico",
    status: "Convergente",
    statusTone: "success",
    documentsCount: 9,
    recentActivity: "Atualizado ontem",
    readiness: 91,
    confidence: 94,
    timelineConsistency: 99,
    pendingReview: 1,
    regressions: 0,
    artwork: "aurora",
    coverLabel: "Parecer",
    updatedAt: "2026-04-09",
    moments: ["parecer emitido", "CID consistente", "protocolo administrativo"],
    categories: ["continue", "high-confidence"],
    summary:
      "Caso com forte aderência entre documentos, eventos e campos críticos. Adequado para demonstração de confiança documental.",
    stats: [
      { label: "Prontidão jurídica", value: "91/100" },
      { label: "Timeline consistente", value: "99/100" },
      { label: "Pendências", value: "1" },
    ],
    documents: [
      {
        id: "doc-parecer-bruno",
        title: "Parecer médico pericial",
        type: "Parecer médico",
        pages: 5,
        fingerprint: "sha256: 8aa0...11d9",
        custodyState: "Preservado com hash local",
        processingStatus: "Timeline pública projetada",
        origin: "digital_nativo",
        issuedAt: "2026-02-14",
        warnings: [],
        ocrMode: "native_text",
        canonicalSignals: [
          { field: "document_date", value: "2026-02-14", state: "observed" },
          { field: "patient", value: "BRUNO CESAR MOURA", state: "observed" },
          { field: "cids", value: "F41.1", state: "observed" },
        ],
        pagesData: [
          {
            number: 3,
            title: "Conclusão pericial",
            snippet:
              "Concluo haver incapacidade parcial temporária, com repercussão ocupacional, relacionada ao CID F41.1.",
            evidenceBox: "bbox [94, 198, 826, 310]",
          },
        ],
        relatedEvents: ["ev-parecer-emitido", "ev-incapacidade-inferida"],
      },
    ],
    events: [
      {
        id: "ev-parecer-emitido",
        date: "2026-02-14",
        type: "parecer_emitido",
        title: "Parecer médico emitido",
        description: "Emissão documental observada e ancorada.",
        state: "observed",
        confidence: 0.97,
        provenanceStatus: "anchored",
        reviewState: "confirmed",
        evidenceRef: "Parecer médico pericial · pág. 1",
      },
      {
        id: "ev-incapacidade-inferida",
        date: "2026-02-14",
        type: "incapacidade_laboral",
        title: "Incapacidade parcial temporária",
        description: "Inferência controlada derivada do parecer; nunca exibida como fato observado.",
        state: "inferred",
        confidence: 0.76,
        provenanceStatus: "derived_from_anchored_document",
        reviewState: "needs_review",
        evidenceRef: "Parecer médico pericial · pág. 3",
      },
    ],
    reviewItems: [
      {
        id: "rv-incapacidade",
        field: "event:incapacidade_laboral",
        value: "parcial temporária",
        reason: "Evento inferido a partir do parecer, exige chancela humana antes de uso probatório.",
        state: "needs_review",
        provenanceStatus: "inferred",
      },
    ],
  },
  {
    id: "data-oliveira",
    title: "Divergência de data | Clara Oliveira",
    subtitle: "Caso sentinela para data documental versus nascimento",
    client: "Clara Oliveira",
    type: "Regressão crítica monitorada",
    status: "Atenção crítica",
    statusTone: "danger",
    documentsCount: 4,
    recentActivity: "Atualizado há 2 h",
    readiness: 58,
    confidence: 74,
    timelineConsistency: 68,
    pendingReview: 5,
    regressions: 2,
    artwork: "ripple",
    coverLabel: "Sentinela",
    updatedAt: "2026-04-10",
    moments: ["birth_date bloqueada", "document_date insegura", "review obrigatório"],
    categories: ["review", "critical"],
    summary:
      "Caso desenhado para evidenciar que data de nascimento não pode ser promovida a data documental. Ideal para demonstrar disciplina semântica da Relluna.",
    stats: [
      { label: "Prontidão jurídica", value: "58/100" },
      { label: "Timeline consistente", value: "68/100" },
      { label: "Pendências", value: "5" },
    ],
    documents: [
      {
        id: "doc-guia-clara",
        title: "Guia de encaminhamento escaneada",
        type: "Documento composto",
        pages: 3,
        fingerprint: "sha256: 11ca...9931",
        custodyState: "Preservado com hash local",
        processingStatus: "Warning semântico ativo",
        origin: "digitalizado",
        issuedAt: "2024-03-05",
        warnings: [
          "Data de nascimento 1980-01-20 detectada e explicitamente bloqueada como data documental.",
          "Timeline pública mantém review_state pendente para document_date.",
        ],
        ocrMode: "ocr_heavy",
        canonicalSignals: [
          { field: "document_date", value: "2024-03-05", state: "observed_with_review" },
          { field: "birth_date", value: "1980-01-20", state: "observed_non_documental" },
          { field: "patient", value: "CLARA OLIVEIRA", state: "observed" },
        ],
        pagesData: [
          {
            number: 1,
            title: "Cabeçalho administrativo",
            snippet: "Data de emissão: 05/03/2024. Paciente: Clara Oliveira. Nascimento: 20/01/1980.",
            evidenceBox: "bbox [84, 88, 790, 176]",
          },
        ],
        relatedEvents: ["ev-document-date-clara"],
      },
    ],
    events: [
      {
        id: "ev-document-date-clara",
        date: "2024-03-05",
        type: "document_issue_date",
        title: "Data documental sob revisão",
        description: "A data documental permanece distinta da data de nascimento e retida em revisão humana.",
        state: "observed",
        confidence: 0.62,
        provenanceStatus: "anchored",
        reviewState: "needs_review",
        evidenceRef: "Guia de encaminhamento escaneada · pág. 1",
      },
      {
        id: "ev-birth-date-blocked",
        date: "1980-01-20",
        type: "birth_date_detected",
        title: "Data de nascimento detectada e bloqueada",
        description: "Sinal observável administrativo. Não é promovido à timeline probatória como document_issue_date.",
        state: "observed",
        confidence: 0.99,
        provenanceStatus: "anchored",
        reviewState: "confirmed",
        evidenceRef: "Guia de encaminhamento escaneada · pág. 1",
      },
    ],
    reviewItems: [
      {
        id: "rv-document-date-clara",
        field: "entity:document_date",
        value: "2024-03-05",
        reason: "OCR pesado e proximidade com birth_date exigem validação humana.",
        state: "needs_review",
        provenanceStatus: "anchored",
      },
      {
        id: "rv-birth-date-guardrail",
        field: "guardrail:birth_date_not_document_date",
        value: "active",
        reason: "Caso sentinela para impedir regressão semântica crítica.",
        state: "confirmed",
        provenanceStatus: "rule_guardrail",
      },
    ],
  },
];

export const collections = [
  {
    id: "continue",
    title: "Continue de onde parou",
    description: "Casos recentemente acessados com sinais confiáveis e trabalho em aberto.",
    caseIds: ["afastamento-lima", "parecer-moura"],
  },
  {
    id: "review",
    title: "Fila de revisão humana",
    description: "Itens sensíveis onde inferência controlada ou conflito semântico ainda exigem operador.",
    caseIds: ["data-oliveira", "afastamento-lima"],
  },
  {
    id: "critical",
    title: "Sentinelas de regressão",
    description: "Casos usados para demonstrar disciplina documental e prevenir regressões críticas.",
    caseIds: ["data-oliveira"],
  },
];

export const billing = {
  currentPlan: "Pro",
  workspace: "Atlas Perícias",
  renewalDate: "22 abr 2026",
  seats: { used: 8, total: 12 },
  cases: { used: 147, total: 300 },
  documents: { used: 1842, total: 5000 },
  paymentMethod: "Visa final 2491",
  invoices: [
    { id: "INV-2026-041", period: "Mar 2026", amount: "R$ 3.480", status: "Pago" },
    { id: "INV-2026-032", period: "Fev 2026", amount: "R$ 3.480", status: "Pago" },
    { id: "INV-2026-021", period: "Jan 2026", amount: "R$ 3.120", status: "Pago" },
  ],
};

export const settingsSections = [
  {
    title: "Perfil",
    items: ["Nome e assinatura", "Idioma de revisão", "Alertas pessoais", "Atalhos de teclado"],
  },
  {
    title: "Workspace",
    items: ["Domínio confiável", "Políticas de retenção", "Rótulos de benchmark interno", "Modelos de caso"],
  },
  {
    title: "Equipe",
    items: ["Convites pendentes", "Perfis e permissões", "Triagem de revisão humana", "Fila por especialidade"],
  },
  {
    title: "Segurança",
    items: ["2FA", "Sessões ativas", "Exportações auditáveis", "Logs de custódia"],
  },
];

export const plans = [
  {
    name: "Starter",
    price: "R$ 790",
    blurb: "Para células enxutas que precisam validar casos com evidência navegável.",
    features: ["25 casos ativos", "600 documentos/mês", "3 membros", "Timeline pública básica"],
  },
  {
    name: "Pro",
    price: "R$ 3.480",
    blurb: "Para operações médico-jurídicas que precisam revisão disciplinada e biblioteca viva de casos.",
    features: ["300 casos ativos", "5.000 documentos/mês", "12 membros", "Fila de revisão e billing consolidado"],
    featured: true,
  },
  {
    name: "Enterprise",
    price: "Sob consulta",
    blurb: "Para perícias, seguradoras e escritórios com controles avançados e governança dedicada.",
    features: ["Casos ilimitados", "SLA dedicado", "SSO e auditoria estendida", "Políticas customizadas"],
  },
];
