from __future__ import annotations

from enum import Enum


class DocType(str, Enum):
    # 1. Pessoais e representação
    DOC_PESSOAL_RG = "DOC_PESSOAL_RG"
    DOC_PESSOAL_CPF = "DOC_PESSOAL_CPF"
    DOC_PESSOAL_CNH = "DOC_PESSOAL_CNH"
    DOC_COMPROVANTE_RESIDENCIA = "DOC_COMPROVANTE_RESIDENCIA"
    DOC_PROCURACAO = "DOC_PROCURACAO"
    DOC_CONTRATO_HONORARIOS = "DOC_CONTRATO_HONORARIOS"
    DOC_DECLARACAO_HIPOSSUFICIENCIA = "DOC_DECLARACAO_HIPOSSUFICIENCIA"

    # 2. Trabalhistas
    TRAB_CTPS = "TRAB_CTPS"
    TRAB_TRCT = "TRAB_TRCT"
    TRAB_HOLERITE = "TRAB_HOLERITE"
    TRAB_FICHA_REGISTRO = "TRAB_FICHA_REGISTRO"

    # 3. Previdenciários
    PREV_CAT = "PREV_CAT"
    PREV_CNIS = "PREV_CNIS"
    PREV_CARTA_CONCESSAO = "PREV_CARTA_CONCESSAO"
    PREV_CARTA_INDEFERIMENTO = "PREV_CARTA_INDEFERIMENTO"
    PREV_LAUDO_SABI = "PREV_LAUDO_SABI"
    PREV_PROCESSO_ADM_INTEGRAL = "PREV_PROCESSO_ADM_INTEGRAL"

    # 4. Médicos
    MED_ATESTADO = "MED_ATESTADO"
    MED_RECEITUARIO = "MED_RECEITUARIO"
    MED_PRONTUARIO_CLINICO = "MED_PRONTUARIO_CLINICO"
    MED_EXAME_IMAGEM = "MED_EXAME_IMAGEM"
    MED_AUDIOMETRIA = "MED_AUDIOMETRIA"
    MED_LAUDO_ASSISTENTE_TECNICO = "MED_LAUDO_ASSISTENTE_TECNICO"

    # 5. SST
    SST_ASO_ADMISSIONAL = "SST_ASO_ADMISSIONAL"
    SST_ASO_DEMISSIONAL = "SST_ASO_DEMISSIONAL"
    SST_ASO_RETORNO = "SST_ASO_RETORNO"
    SST_ASO_PERIODICO = "SST_ASO_PERIODICO"
    SST_PCMSO = "SST_PCMSO"
    SST_PGR_PPRA = "SST_PGR_PPRA"
    SST_AET = "SST_AET"
    SST_LTCAT = "SST_LTCAT"
    SST_PPP = "SST_PPP"
    SST_FICHA_EPI = "SST_FICHA_EPI"

    # 6. Provas complementares
    PROVA_BOLETIM_OCORRENCIA = "PROVA_BOLETIM_OCORRENCIA"
    PROVA_PRINT_MENSAGEM = "PROVA_PRINT_MENSAGEM"
    PROVA_FOTO_AMBIENTE = "PROVA_FOTO_AMBIENTE"
    PROVA_ATA_NOTARIAL = "PROVA_ATA_NOTARIAL"

    UNKNOWN = "UNKNOWN"